elasticsearch:
  namespace: logging
  master:
    masterOnly: false
    replicaCount: 1
    resources:
      limits:
        memory: 3Gi
      requests:
        memory: 2Gi
    extraEnvVars:
      - name: ES_JAVA_OPTS
        value: "-Xms1g -Xmx2g"
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0

kibana:
  namespace: logging
  elasticsearch:
    hosts:
      - "efk-stack-elasticsearch.logging.svc.cluster.local"
    port: 9200

  extraEnvVars:
    - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
      value: "b5984c2a3a449b2f948751f8eec01950"

  extraConfiguration:
    xpack.encryptedSavedObjects.encryptionKey: "b5984c2a3a449b2f948751f8eec01950"

  readinessProbe:
    initialDelaySeconds: 120
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 12

  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 12

  persistence:
    enabled: true
    storageClass: "ebs-csi-gp3"
    accessModes:
      - ReadWriteOnce
    size: 8Gi

fluent-bit:
  namespace: logging

  logLevel: debug

  securityContext:
    fsGroup: 0
    runAsNonRoot: true

  containerSecurityContext:
    runAsUser: 1001
    runAsGroup: 0
    allowPrivilegeEscalation: false
    privileged: false

  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush 1
          Log_Level debug
          Parsers_File /opt/bitnami/fluent-bit/conf/parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
          Health_Check On

    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/blackjack-stack-app*.log
          Read_From_Head Off
          multiline.parser docker, cri
          Tag kube.*
          Parser json
          Mem_Buf_Limit 100MB
          Skip_Long_Lines On
          Refresh_Interval 5

    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off

    outputs: |
      [OUTPUT]
          Name stdout
          Match kube.*
          Format json_lines

      [OUTPUT]
          Name es
          Match kube.*
          Index blackjack-logs
          Host efk-stack-elasticsearch.logging.svc.cluster.local
          Port 9200
          tls Off
          tls.verify Off
          Logstash_Format On
          Logstash_Prefix blackjack
          Suppress_Type_Name On
          Retry_Limit 5

  extraVolumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: containers
      mountPath: /var/lib/docker/containers
      readOnly: true

  extraVolumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: containers
      hostPath:
        path: /var/lib/docker/containers

  persistence:
    enabled: true
    storageClass: "gp2"
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    mountPath: /bitnami/fluent-bit

  volumePermissions:
    enabled: true
