apiVersion: v2
name: monitor-stack
description: Umbrella chart for Prometheus and Grafana monitoring via kube-prometheus-stack
type: application
version: 1.0.0

dependencies:
  - name: kube-prometheus-stack
    version: 75.12.0   # Use the latest compatible version for your cluster!
    repository: https://prometheus-community.github.io/helm-charts
