services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - env.env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network

  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  mongo-data: