---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    mongo-uri: AgBjAvRIAFK/E2Ss4hha9d82HdHUs0Q7nf3IIP1c2kynC0Z72B5+TZkTkESXcsWz4DROQpgf5hI2H7Zq+Tdr/o1O60VfkeYVQsgf/nqJc+zYD0HwuCyhbCVaOi+jsdxTiXCz8CLkUr6YGqmqqVe08EkqYfwzra3YEtPh1ySR+kdYWcYMlPaLk/swukg0qicAFPjT807T1h+lPFr2iRV5gnUPMP6j5cvx3ThdI6hsz7YJjy0q23JlQnD2ltwTkl5BYhx2e21GUbUrte3fIABXQ6f4YdB4ytTpUo8qGFCmhyfliU/BtOI8omupDUg5nICUHNHsfMRJ26WTBkhCOZ9rxlqOSZZZtuNwleOLqgLjD807Yq5C2nej1LTM+dhFH6NnDJOU7aEO771CYhXhW9BQj8TZROHP1SQe6ItHqqP4qBeVVIbgYzJ6pWZoJVYZzqy6OUEdm2y5yqgopJaZ8qLg+KA4DJqu50zb2sUnk21yMrRhoOpXyX12osOKsGT47mdpk+isCAEQek7duA67cuUTJ8mPmFN5kYyrh3rWyrJa0bbxkOC0n1XpkMKGftvjOhJW1/Qx/9MgMCArvOKEW5xKvrG2ABAp8XMPL0ouV+PF6zjKITv5wG/hSDj0LWEDocyzX2JJglm/sf80y01qymCeeM/T7a4gbSY5R+heZ1JIhtgOrstaKhsNpAYW7yP+3XGhVAgNM+0NaSCqFW4xXgBYqIkTkmPFqzS7+sydcWx2XoKsyT+4ZV5IeFGcnvz4FjjdZ2lqISMQ8ysdxsnySBClLIRcYfCo8S2iWvZT2iE8ZuvejgAHTaKkSmO5lrgs9UzgzQfn2VqHkWK2ivKb4A==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
