---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    mongo-uri: AgAjFEfa1zA5JuI19pKrbMgDKrw3zQ03wqJD38a+dbQr0ZbONEy2hnfT/zpdWyRx+obanO3kJD6AK/HH6z4qtJ1Q1Ow6RwDqIOzLERzmbf40fwg24Em9VxPrz6lYQhOoPUTUBNtqL9QCOnCGFgIyIu5PGc78SZOlKFJ97CXpDeUmuqjwzr7ptyKoz5nRtiqup4JhcKfqXfltKPr+CV4MPliGe8x61PLU7n6FoAAxQdHg8ydJdVj2x5Je1QvJM4dJe7yHj1gDwpZ81CHE8+ET7Ru1uQreclvdtBS9Ah+luy9U1koWXGdj0MZoXOMqTBEWLZmMY8qmObieYwhBbV6/xdTS5bNh5cHkyjMUxBOZm5ZQINuE/UoKer3jKJuJ1Fa+a0b8P4EHD6whQZqz3YHW0yT3aW+4dEQJXR87TKpuWFihNeJ+Hcmo21tOH8THdBAfwBW97lT+XLHhOznFr3SjqAyK6WOJo0aVOH71KVY3tBqQSQY9lLDVOl9DpXXEc6kceIhKuOqDUISY+XTpSBoLxqpFzKN84HwFCNe5k7yDmUhumGxuJGVrPpZzegcKisACW5fIDzEToG0bdAs9zStb5tNizoPjYkAZM3l+uIFb0UUM1XcBwMr5H4z5gWZGrSTe0nyMsAYru6ApjLIFgut+PzXC+D3DQeEAYfQh1B69BvRyrRpqBCJwHHqGdKlywVRR8ez9+pL7X51JEbXltjmR4SR9fq8UD/LGix1N2iPmoMP/q88VwUGdZzh8lZo1Pf2s/0qOh80Nfy73YwKem+8PKiT5gwwhqp91/9zvvHycqaJwmd+wtmHcu05yefHK1hCdJogNcO1AVF/CcGd6+yUtavv0iLLHQogoA8tUGJuXdLHBCMkrLc4XrVUluOAOUO0wDSxcwKSV
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
    type: Opaque
