apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:alexmachulsky/blackjack-k8s.git'
    targetRevision: main
    path: efk-stack
    helm:
      valueFiles:
        - values.yaml
      releaseName: efk-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging        # Change if you use a different namespace
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=true