{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "blackjack.fullname" . }}-servicemonitor
  labels:
    release: {{ .Values.serviceMonitor.release | default "monitor-stack" }}
    app: {{ include "blackjack.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "blackjack.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
